// Credits list
addCreditsLine("<just:center><bitmap:ACCM_Eagle><sbreak>");
addCreditsLine("<font:Univers:22>");
addCreditsLine("");
addCreditsLine("");
addCreditsLine("");
addCreditsLine("");
addCreditsLine("");
addCreditsLine("");
addCreditsLine("");
addCreditsLine("");
addCreditsLine("");
addCreditsLine("");
addCreditsLine("");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Main Developer/Mod Founder<spop><spop>");
addCreditsLine("Blnukem");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Secondary Developer/Mod Co-Founder<spop><spop>");
addCreditsLine("Eolk");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Development Assistant<spop><spop>");
addCreditsLine("Dark Dragon DX");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Original Construction Mod Development Team<spop><spop>");
addCreditsLine("Mostlikely, JackTL, and Construct");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Original CCM Development Team<spop><spop>");
addCreditsLine("Dondelium_X, FalconBlade, and Ur_A_Dumb");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>ACCM Forum and ACCM FTP Server Host<spop><spop>");
addCreditsLine("Krash123");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Mod Testers<spop><spop>");
addCreditsLine("Blnukem");
addCreditsLine("Eolk");
addCreditsLine("Zaxxman");
addCreditsLine("Dark Dragon DX");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Concepts and Ideas<spop><spop>");
addCreditsLine("Bungie.net and the Halo Universe");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Games/Programs Which Provided Sounds<spop><spop>");
addCreditsLine("Quake 3: Arena - Provided Various GUI and Zombie Sounds");
addCreditsLine("Quake 3: Team Arena - Provided Various GUI Sounds");
addCreditsLine("Call of Duty 4: Modern Warfare - Provided Explosion and Weapon Sounds");
addCreditsLine("Acid 2.0 - Used Create and Edit Various .wav and .mp3 Sounds");
addCreditsLine("");
addCreditsLine("<spush><font:Univers condensed:22><spush><color:18A27B>Other Thanks<spop><spop>");
addCreditsLine("Emperors Champ   \'Alviss\'");
addCreditsLine("CMDRBOB");
addCreditsLine("Electricutioner");
addCreditsLine("Ronnies07");
addCreditsLine("Avenger777   \'Naosyth\'");
addCreditsLine("Lord Sega^   \'Stingwraith\'");
addCreditsLine("BlinX^");
addCreditsLine("Destos");
addCreditsLine("");
addCreditsLine("");
addCreditsLine("");
addCreditsLine("");
addCreditsLine("");
addCreditsLine("<spush><spush>And a special thanks to the entire Construction Community.<spop><spop>");
addCreditsLine("");
addCreditsLine("");
addCreditsLine("");
addCreditsLine("");
addCreditsLine("");
addCreditsLine("");
addCreditsLine("");
addCreditsLine("");
addCreditsLine("");
addCreditsLine("");
